version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      jackson:
        patterns:
          - "com.fasterxml.jackson*"
      slf4j:
        patterns:
          - "org.slf4j*"