name: Build and check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 22

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9

      - name: Run checks
        run: ./gradlew build check shadowJar

# todo: disabled whilst investigating libvips
#      - name: Run samples
#        run: |
#          sudo apt install imagemagick
#          magick --version
#          ./run_samples.sh